name: Get pre-release Branch
description: Gets the name of the current pre-release branch.

outputs:
  branch_name:
    description: The name of the current pre-release branch.
    value: ${{ steps.pre_release_pull_request.outputs.branch_name }}
  url:
    description: The URL of the current pre-release pull request.
    value: ${{ steps.pre_release_pull_request.outputs.pull_request_url }}

runs:
  using: "composite"
  steps:
    - name: Check for existing pull request
      id: pre_release_pull_request
      uses: actions/github-script@v6
      with:
        script: |
          const issues = await github.request('GET /repos/{owner}/{repo}/issues', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: 'Pre-release'
          });

          const preReleaseIssue = issues.data.find(issue => {
            return issue.title.startsWith('Pre-release');
          });

          if (!preReleaseIssue) {
            return;
          }

          try {
            const pullRequest = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: preReleaseIssue.number
            });

            console.log(pullRequest.data);
            core.setOutput('branch_name', pullRequest.data.head.ref);
            core.setOutput('url', pullRequest.data.html_url);
          } catch(error) {
            core.setFailed('Found non-pull request issue with the Pre-release label. ' + preReleaseIssue.html_url);
          }

