name: Get pre-release Branch
description: Gets the name of the current pre-release branch.

outputs:
  branch_name:
    description: The name of the current pre-release branch.
    value: ${{ steps.pre_release_pull_request.outputs.branch_name }}
  pull_request_url:
    description: The URL of the current pre-release pull request.
    value: ${{ steps.pre_release_pull_request.outputs.pull_request_url }}

runs:
  using: "composite"
  steps:
    - name: Check for existing pull request
      id: pre_release_pull_request
      uses: actions/github-script@v6
      with:
        script: |
          const issues = await github.request('GET /repos/{owner}/{repo}/issues', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: 'Pre-release'
          });
          issues.data.forEach(issue => {
            console.log(issue);
            if (issue.title.startsWith('Pre-release')) {
              core.setOutput('branch_name', issue.head.ref);
              core.setOutput('pull_request_url', issue.html_url);
              return;
            }
          });
