name: Get release-candidate Branch
description: Gets the name of the current release-candidate branch.

outputs:
  branch:
    description: The name of the current release-candidate branch.
    value: ${{ steps.pre_release_pull_request.outputs.branch }}
  sha:
    description: The SHA of the current release-candidate branch.
    value: ${{ steps.pre_release_pull_request.outputs.sha }}
  url:
    description: The URL of the current release-candidate pull request.
    value: ${{ steps.pre_release_pull_request.outputs.url }}

runs:
  using: "composite"
  steps:
    - name: Check for existing pull request
      id: pre_release_pull_request
      uses: actions/github-script@v6
      with:
        script: |
          const issues = await github.request('GET /repos/{owner}/{repo}/issues', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: 'release-candidate'
          });

          const preReleaseIssue = issues.data.find(issue => {
            return issue.title.startsWith('release-candidate');
          });

          if (!preReleaseIssue) {
            return;
          }

          try {
            const pullRequest = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: preReleaseIssue.number
            });

            core.setOutput('branch', pullRequest.data.head.ref);
            core.setOutput('sha', pullRequest.data.head.sha);
            core.setOutput('url', pullRequest.data.html_url);
          } catch(error) {
            core.setFailed('Found non-pull request issue with the release-candidate label. ' + preReleaseIssue.html_url);
          }

