name: Build Docker Image

on:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Remove Build Label
        if: github.event.label.name == 'Build Docker Image'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.payload.organization.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              name: context.payload.label.name
            })
            console.log('Remove ' + context.payload.label.name + ' label')
      - name: Build Image
        run: |
          echo "Build Docker image"
