name: Build Docker Image

on:
  push:
    branches:
      - main
      - prerelease
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: github.event.label.name == 'QA Ready' || github.event.label.name == 'Build Docker Image' || github.event.ref == 'refs/heads/prerelease' || github.event.ref == 'refs/heads/main'
    steps:
      - name: Remove Build Label
        if: github.event.label.name
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.payload.organization.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              name: context.payload.label.name
            })
            console.log('Remove ' + context.payload.label.name + ' label')
      - name: Build Image
        run: |
          echo "Build Docker image"
      - name: Push Image
        run: |
          echo "Push Docker image"
