name: Build Docker Image

on:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check for build labels
        id: check_labels
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name)
            const buildLabel = labels.find(label => label === 'Build Docker Image')
            const qaReadyLabel = labels.find(label => label === 'QA Ready')
            if (buildLabel || qaReadyLabel) {
              core.setOutput('build', 'true')
            } else {
              core.setOutput('build', 'false')
            }
      - name: Remove Build Label
        if: github.event.label.name == 'Build Docker Image'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              name: context.payload.label.name
            })
            console.log('Remove ' + context.payload.label.name + ' label')
      - name: Build Image
        if: steps.check_labels.outputs.build == 'true'
        run: |
          echo "Build Docker image"
