name: Create Pre-Release Pull Request

on:
  workflow_dispatch:

jobs:
  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check for existing pull request
        uses: actions/github-script@v6
        with:
          script: |
            const issues = await github.request('GET /repos/{owner}/{repo}/issues', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'Pre-release'
            });
            issues.data.forEach(issue => {
              console.log(issue);
              if (issue.title === 'Pre-release') {
                core.setFailed('Pull request already exists: ' + issue.html_url);
              }
            });
      - name: Create branch
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const branchName = 'pre-release-' + (new Date()).toISOString().slice(0, 10);
            core.exportVariable('PRE_RELEASE_BRANCH', branchName);
            try {
              const branchInfo = await github.request('GET /repos/{owner}/{repo}/branches/{branch}', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: branchName
              });
              core.notice('Branch '+ branchName + ' already exists');
            } catch(error) {
              await github.request('POST /repos/{owner}/{repo}/git/refs', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/heads/' + branchName,
                sha: context.sha
              });
              core.notice('Created pre-release branch: ' + branchName);
            }
            return branchName;
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.PRE_RELEASE_BRANCH }}
      - name: Touch release
        run: |
          echo ${PRE_RELEASE_BRANCH} > RELEASE
          git add RELEASE
          git commit -m "Set release"
          git push origin ${PRE_RELEASE_BRANCH}
      - name: Create pull request
        uses: actions/github-script@v6
        with:
          script: |
            const branchName = process.env.PRE_RELEASE_BRANCH;
            const pullRequest = await github.request('POST /repos/{owner}/{repo}/pulls', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Pre-release',
              head: branchName,
              base: 'main',
              labels: ['Pre-release'],
              body: 'This is a pre-release pull request. It will be merged when the release is ready.'
            });
            core.notice('Created pull request: ' + pullRequest.data.html_url);
