name: Create Pre-Release Pull Request

on:
  workflow_dispatch:

jobs:
  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check for existing pull request
        uses: actions/github-script@v6
        with:
          script: |
            const pullRequests = await github.request('GET /repos/{owner}/{repo}/pulls', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'Pre-release'
            });
            if (pullRequests.data.length > 0) {
              console.log('Pull request already exists: ' + pullRequests.data[0].html_url);
              process.exit(1);
            }
      - name: Create branch
        uses: actions/github-script@v6
        with:
          script: |
            branchName = 'pre-release-' + (new Date()).toISOString().slice(0, 10);
            try {
              const branchInfo = await github.request('GET /repos/{owner}/{repo}/branches/{branch}', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: branchName
              });
              //console.log('Branch '+ branchName + ' already exists');
            } catch(error) {
              //await github.request('POST /repos/{owner}/{repo}/git/refs', {
              //  owner: context.repo.owner,
              //  repo: context.repo.repo,
              //  ref: 'refs/heads/' + branchName,
              //  sha: context.sha
              //});
              //console.log('Created pre-release branch: ' + branchName);
            }
      - name: Create pull request
        uses: actions/github-script@v6
        with:
          script: |
            const pullRequest = await github.request('POST' /repos/{owner}/{repo}/pulls', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Pre-release',
              head: branchName,
              base: 'main',
              labels: ['Pre-release'],
              body: 'This is a pre-release pull request. It will be merged when the release is ready.'
            });
            console.log('Created pull request: ' + pullRequest.data.html_url);
