name: "* Deploy To Production"
run-name: "Deploy To Production"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to deploy (defaults to the current release)
        required: false
  release:
    types: released

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency:
      group: "Deploy to production"
      cancel-in-progress: true
    environment: production
    steps:
      - name: Load local GitHub actions
        uses: actions/checkout@v3
        with:
          sparse-checkout: .github
      - name: Get release SHA
        id: release_sha
        uses: ./.github/actions/get-release-sha
        with:
          tag: ${{ github.event.inputs.tag || github.event.release.tag_name }}
      - name: Build Image
        uses: ./.github/actions/deploy-application
        with:
          ref: ${{ steps.release_sha.outputs.ref }}
          sha: ${{ steps.release_sha.outputs.sha }}
