name: "* Deploy To Production"
run-name: "Deploy To Production"

on:
  workflow_dispatch:
  release:
    types: released

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Run deployment
        run: |
          echo "Deploying ${GITHUB_REF} to production (${GITHUB_SHA})"
