name: "* Deploy To Development"
run-name: "Deploy to ${{ github.event.inputs.environment }} (${{ github.sha }})"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - alfa
          - beta
          - gamma
          - delta

jobs:
  build-image:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency:
      group: "Build Docker Image ${{ github.sha }}"
    steps:
      - name: Load local GitHub actions
        uses: actions/checkout@v3
        with:
          sparse-checkout: .github
      - name: Build Docker image
        uses: ./.github/actions/build-docker-image
        with:
          sha: ${{ github.sha }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-image
    concurrency:
      group: "Deploy ${{ github.event.inputs.environment }}"
      cancel-in-progress: true
    environment: development
    steps:
      - name: Load local GitHub actions
        uses: actions/checkout@v3
        with:
          sparse-checkout: .github
      - name: Deploy application
        uses: ./.github/actions/deploy-application
        with:
          environment: ${{ github.event.inputs.environment }}
          sha: ${{ github.sha }}
          ref: ${{ github.ref }}