name: Deploy Development From Label
run-name: ${{ github.event.label.name }}

on:
  pull_request:
    types:
      - labeled

jobs:
  get-environment:
    name: Get environment
    runs-on: ubuntu-latest
    if: startsWith(github.event.label.name, 'Deploy to ')
    outputs:
      value: ${{ steps.environment.outputs.value }}
    permissions:
      pull-requests: write
    steps:
      - name: Get environment
        id: environment
        env:
          LABEL: ${{ github.event.label.name }}
        run: |
          echo "value=${LABEL/#'Deploy to '}" >> $GITHUB_OUTPUT
      - name: Remove Deploy Label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              name: context.payload.label.name
            })
  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    concurrency:
      group: "Build Docker image ${{ github.sha }}"
    steps:
      - name: Load local GitHub actions
        uses: actions/checkout@v3
        with:
          sparse-checkout: .github
      - name: Build Image
        uses: ./.github/actions/build-docker-image
        with:
          sha: ${{ github.sha }}
  deploy:
    name: Deploy to development
    runs-on: ubuntu-latest
    needs:
      - get-environment
      - build-image
    if: startsWith(github.event.label.name, 'Deploy to ')
    concurrency:
      group: "Deploy to ${{ needs.get-environment.outputs.environment }}"
    environment: development
    steps:
      - name: Load local GitHub actions
        uses: actions/checkout@v3
        with:
          sparse-checkout: .github
      - name: Deploy
        uses: ./.github/actions/deploy-application
        with:
          environment: ${{ needs.get-environment.outputs.environment }}
          sha: ${{ github.sha }}
          ref: ${{ github.ref }}
