name: Deploy To Staging

on:
  push:
    branches:
      - main
      - prerelease

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check for prerelease branch
        id: check_for_cutover
        if: github.event.ref == 'refs/heads/main'
        run: |
          BRANCH_EXISTS=$(git ls-remote --heads origin prerelease | wc -l)
          if [ "$BRANCH_EXISTS" -gt 0 ]; then
            echo "::set-output name=prerelease::true"
          else
            echo "::set-output name=prerelease::false"
          fi
      - name: Build Docker image
        if: steps.check_for_cutover.outputs.prerelease == 'false' || github.event.ref == 'refs/heads/prerelease'
        run: |
          echo "Build Docker image"
      - name: Run deployment
        if: steps.check_for_cutover.outputs.prerelease == 'false' || github.event.ref == 'refs/heads/prerelease'
        run: |
          echo "Deploying ${GITHUB_REF} to staging (${GITHUB_SHA})"
