name: "* Deploy To Production"
run-name: "Deploy To Production"

on:
  workflow_dispatch:
  release:
    types: released

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Load local GitHub actions
        uses: actions/checkout@v3
        with:
          sparse-checkout: .github
      - name: Build Image
        uses: ./.github/actions/deploy-application
        with:
          environment: production
