name: Deploy To Staging

on:
  push:
    branches:
      - main
      - pre-release
      - hotfix

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get branch to build
        id: ref_to_build
        if: github.event.ref == 'refs/heads/main'
        uses: actions/github-script@v6
        with:
          script: |
            async function getBranch(branchName) {
              try {
                const { data } = await github.repos.getBranch({
                  owner: owner,
                  repo: repo,
                  branch: branchName,
                });
                return data;
              } catch (error) {
                return null;
              }
            }

            const hotfixBranch = await getBranch('hotfix');
            if (hotfixBranch) {
              return 'hotfix';
            }

            const preReleaseBranch = await getBranch('pre-release');
            if (preReleaseBranch) {
              return 'pre-release';
            }

            return 'main';
      - name: Build Docker image
        if: github.event.ref == steps.ref_to_build.outputs.result
        run: |
          echo "Build Docker image"
      - name: Run deployment
        if: github.event.ref == steps.ref_to_build.outputs.result
        run: |
          echo "Deploying ${GITHUB_REF} to staging (${GITHUB_SHA})"
