name: "* Deploy To Staging"
run-name: "Deploy To Staging"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-candidate
      - hotfix

jobs:
  get-branch:
    name: Check if branch should be built
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.ref_to_build.outputs.ref }}
      sha: ${{ steps.ref_to_build.outputs.sha }}
    steps:
      - name: Get current staging branch
        id: ref_to_build
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            let buildBranch = null;
            let ref = null;
            let sha = null;

            const branches = ['hotfix', 'release-candidate', 'main'];
            for (let i = 0; i < branches.length; i++) {
              branchName = branches[i];
              try {
                const { data: branch } = await github.request('GET /repos/{owner}/{repo}/branches/{branch}', {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  branch: branchName
                });
                buildBranch = branchName;
                console.log(branch)
                ref = branch.ref;
                sha = branch.commit.sha;
                break;
              } catch (error) {
                if (error.status !== 404) {
                  throw error;
                }
              }
            }

            core.notice(`ref: ${ref}, context.ref: ${context.ref}`)
            if (context.ref === ref) {
              core.notice(`Current staging branch is ${buildBranch}`);
            } else {
              core.notice(`Not deploying to staging; current staging branch is ${buildBranch}`);
            }

            core.setOutput('ref', ref)
            core.setOutput('sha', sha);
  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: get-branch
    if: needs.get-branch.outputs.sha
    concurrency:
      group: "Build Docker image ${{ needs.get-branch.outputs.sha }}"
    steps:
      - name: Load local GitHub actions
        uses: actions/checkout@v3
        with:
          sparse-checkout: .github
      - name: Build Docker image
        uses: ./.github/actions/build-docker-image
        with:
          sha: ${{ needs.get-branch.outputs.sha }}
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    if: needs.get-branch.outputs.sha
    needs:
      - get-branch
      - build-image
    concurrency:
      group: "Deploy to staging"
      cancel-in-progress: true
    environment: staging
    steps:
      - name: Load local GitHub actions
        if: needs.get-branch.outputs.ref
        uses: actions/checkout@v3
        with:
          sparse-checkout: .github
      - name: Deploy to staging
        if: needs.get-branch.outputs.ref
        uses: ./.github/actions/deploy-application
        with:
          environment: staging
          sha: ${{ needs.get-branch.outputs.sha }}
          ref: ${{ needs.get-branch.outputs.ref }}
