name: Deploy To Production

on:
  release:
    types: released

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run deployment
        run: |
          echo "Deploying ${GITHUB_REF} to production (${GITHUB_SHA})"
