name: "* Hotfix: Create"
run-name: "Create Hotfix From ${{ github.event.ref }}"

on:
  workflow_dispatch:

jobs:
  create:
    name: Create hotfix
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: hotfix
    steps:
      - name: Ensure branching from tag
        uses: actions/github-script@v6
        with:
          script: |
            if (!context.ref.startsWith('refs/tags/')) {
              core.setFailed('This workflow must be run from a tag to ensure the hotfix is branched from a release');
              return;
            }
      - name: Create hotfix branch
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.request('GET /repos/{owner}/{repo}/branches/{branch}', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'hotfix',
              });
              core.setFailed('Hotfix already in progress');
              return;
            } catch (error) {
              if (error.status !== 404) {
                throw error;
              }
            }

            await github.request('POST /repos/{owner}/{repo}/git/refs', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/heads/hotfix',
              sha: context.sha
            });
            core.notice(`Created hotfix branch from ${context.ref}`);
