name: "Hotfix: Finalize"

on:
  workflow_dispatch:

jobs:
  build:
    name: Finalize hotfix
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: hotfix
    steps:
      - name: Delete hotfix branch
        uses: actions/github-script@v6
        with:
          script: |
            let sha = null;
            try {
              const { data: branchInfo } = await github.request('GET /repos/{owner}/{repo}/branches/{branch}', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'hotfix'
              });
              sha = branchInfo.commit.sha;
            } catch (error) {
              if (error.status !== 404) {
                throw error;
              }
              core.setFailed('No hotfix branch exists');
              return;
            }

            /*
            const { data: release } = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'hotfix',
              name: 'Hotfix',
              body: 'Hotfix',
              draft: false,
              prerelease: false
            });
            core.notice(`Created release ${release.id}`);
            */

            await github.request('DELETE /repos/{owner}/{repo}/git/refs/heads/{branch}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'hotfix'
            });
            core.notice('Deleted hotfix branch');
