name: "* Hotfix: Create"
run-name: "Create Hotfix From ${{ github.event.inputs.tag || 'latest release' }}"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to create hotfix from (defaults to the current release)
        required: false

jobs:
  create:
    name: Create hotfix
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: hotfix
    steps:
      - name: Create hotfix branch
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.request('GET /repos/{owner}/{repo}/branches/{branch}', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'hotfix',
              });
              core.setFailed('Hotfix already in progress');
              return;
            } catch (error) {
              if (error.status !== 404) {
                throw error;
              }
            }

            let sha = null;
            let tag = context.payload.inputs?.tag;

            if (!tag) {
              try {
                const { data: releaseInfo } = await github.request('GET /repos/{owner}/{repo}/releases/latest', {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                });
                tag = releaseInfo.tag_name;
              } catch (releaseError) {
                if (error.status !== 404) {
                  throw error;
                }
                core.setFailed('No release found');
                return;
              }
            }

            try {
              const { data: tagInfo } = await github.request('GET /repos/{owner}/{repo}/git/ref/tags/{tag}', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag,
              });
              sha = tagInfo.object.sha;
            } catch (tagError) {
              if (error.status !== 404) {
                throw error;
              }
              core.setFailed(`Tag ${tag} not found`);
              return;
            }

            core.notice(`Creating hotfix branch from ${tag} (${sha})`)
            await github.request('POST /repos/{owner}/{repo}/git/refs', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/heads/hotfix',
              sha: context.sha
            });
            core.notice('Created hotfix branch');
