name: Merge prelease Back To main

on:
  push:
    branches:
      - prerelease

jobs:
  deploy:
    name: Merge
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Merge to main
        id: commit_count
        uses: actions/github-script@v6
        with:
          script: |
            await octokit.request('POST /repos/{owner}/{repo}/merges', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: 'main',
              head: 'prelease',
              commit_message: 'Merged prelease to main.'
            })
