name: Merge pre-release To main

on:
  push:
    branches:
      - pre-release

jobs:
  merge:
    name: Merge branches
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Load local GitHub actions
        uses: actions/checkout@v3
        with:
          sparse-checkout: .github
      - name: Generate a token for the action app
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.ACTION_APP_ID }}
          private_key: ${{ secrets.ACTION_APP_PRIVATE_KEY }}
      - name: Use the token
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api octocat
      - name: Merge pre-release to main
        id: check_pull_request
        uses: ./.github/actions/merge_to_upstream_branch
        with:
          upstream-branch: main2
          source-branch: pre-release
          pull-request-label: Failed Merge
      # - name: Merge pre-release to main
      #   id: commit_count
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       await github.request('POST /repos/{owner}/{repo}/merges', {
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         base: 'main',
      #         head: 'pre-release',
      #         commit_message: 'Merged pre-release to main.'
      #       });
      #       core.notice('Merged pre-release to main');
