name: Merge release-candidate To main

on:
  push:
    branches:
      - release-candidate

jobs:
  merge:
    name: Merge branches
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Load local GitHub actions
        uses: actions/checkout@v3
        with:
          sparse-checkout: .github
      - name: Generate a token for the action app
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.ACTION_APP_ID }}
          private_key: ${{ secrets.ACTION_APP_PRIVATE_KEY }}
      - name: Merge release-candidate to main
        id: merge_to_main
        uses: ./.github/actions/merge_to_upstream_branch
        with:
          upstream-branch: main2
          source-branch: release-candidate
          pull-request-label: Failed Merge
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
