name: Revert Cutover

on:
  workflow_dispatch:

jobs:
  build:
    name: Revert
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete Cutover Branch
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const branchInfo = await github.request('DELETE /repos/{owner}/{repo}/branches/{branch}', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'cutover',
              });
              console.log('Deleted cutover branch')
            } catch (error) {
              console.log('Branch did not exist')
            }
